### ISSUE TITLE
Поднять окружение и залить в гитхаб

### ISSUE THREAD

**Issue by RabigaSB** [sound0terror/LetsPlaySoccer#1]
**Конечный результат:** 

В репозитории есть инициализированные проекты фронта и бэка.

Дерево может выглядеть так:
- репозитории
-- LetsPlaySoccer_front
-- LetsPlaySoccer_back

**Мотивация:** 

На данный момент в проект не инициализирован. 

**Критерии приёмки:**

-  Лишние файлы удалены в React проекте
-  В .gitignore добавлены (фронт и бэк):
       ` node_modules`
        `.idea`
        `.DS_Store`
-  В бэке создать файл с названием server.js
-  Инициализировать npm (npm init)
-  Другие улучшения по усмотрению разработчика

**Планируемое время работы:**

10 мин

**Comment by Rikling** [comment]
приступил в 2:15

**Comment by sound0terror** [comment]
### Закончил в 22:45. из за плохого интернет соединения.
