### ISSUE TITLE
Функционал для логина на бэке

### ISSUE THREAD

**Issue by RabigaSB** [sound0terror/LetsPlaySoccer#10]
**Что нужно сделать?**

Создать серверную часть для логина пользователя.
Функционал:

- незалогиненный пользователь не может просматривать другие страницы приложения;
- если пользователь залогинен он не может попасть на страницу логина;
- обычный пользователь не может зайти на страницу администратора;

**Как это сделать?**
Создать роуты для логина пользователя. написать middleware auth для аутентификации пользователя.

**Зачем это нужно?**

По тз не залогинненый пользователь не может просматривать приложение.

**Критерии приёмки:**

Проверить через постман правильно ли работает логин. 

**Планируемое время работы:**

**Comment by kasienov2001** [comment]
Начал: 17:00 
Закончил: 20:50
Затраченное время: 3 часа 50 минут
