### ISSUE TITLE
Функционал для логина на фронте

### ISSUE THREAD

**Issue by RabigaSB** [sound0terror/LetsPlaySoccer#11]
**Что нужно сделать?**

Создать пользовательскую часть для логина пользователя.

**Как это сделать?**

На фронте:
Создать классовый компонент для логина. 
Компонент для логина должен содержать 1 кнопку и 2 поля ввода:

1. тел номер;
2. пароль,
И надпись **забыли пароль**

**Зачем это нужно?**

Форма логина нужна для аутентификации пользователя.

**Критерии приёмки:**

(текст gerkin сценария)

Функция: Логин пользователя

    Сценарий: Успешный логин

     >  Допустим я нахожусь на странице логина
     >  Если я ввожу "+7777777" в поле "telNumber"
     >  И я ввожу "123" в поле "password"
     >  И я нажимаю на кнопку "Login"
     >  То я вижу текст "Login success"

**Планируемое время работы:**
2:30ч

**Comment by sound0terror** [comment]
Переназначил разработчика

**Comment by Rikling** [comment]
приступил к работе в 4:10

**Comment by Rikling** [comment]
Закончил в 5:30 за 1:20
