### ISSUE TITLE
Функционал для регистрации на бэке

### ISSUE THREAD

**Issue by RabigaSB** [sound0terror/LetsPlaySoccer#12]
**Что нужно сделать?**

Создать серверную  часть для регистрации пользователя.

**Как это сделать?**

Если проект не склонирован, склонировать проект. Запустить базу данных, создать таблицу пользователя которая должна содержать в себе telNumber, displayName, password.
Создать фикстуры для пользователя. Создать роуты для регистрации.

**Зачем это нужно?**

Для регистрации пользователя и записывания данных в бд.

**Критерии приёмки:**

На данном этапе работы проверить работу бэкенда через постман.

**Планируемое время работы:**
2ч

**Comment by Rikling** [comment]
приступил к работе в 16:25

**Comment by Rikling** [comment]
временно приостановлено 6:00

**Comment by kasienov2001** [comment]
Начал: 17:00
Закончил: 20:50
Затраченное время: 3 часа 50 минут
