### ISSUE TITLE
Функционал для регистрации на фронте

### ISSUE THREAD

**Issue by RabigaSB** [sound0terror/LetsPlaySoccer#13]
**Что нужно сделать?**

Создать пользовательскую часть для регистрации пользователя.

**Как это сделать?**

На фронте:
Создать классовый компонент для регистрации. Создать гибкую форму на любой случай.
Компонент для регистрации должен содержать 1 кнопку и 4 поля ввода:

1. тел номер;
2. имя пользователя;
3. пароль;
4. аватар. должен быть type: file

**Зачем это нужно?**

Форма для создания нового пользователя нужна для создания профиля в приложении.

**Критерии приёмки:**

(текст gerkin сценария)

Функция: Регистрация пользователя

    Сценарий: Успешная регистрация

     >  Допустим я нахожусь на странице регистрации
     >  Если я ввожу "testUser" в поле "username"
     >  И я ввожу "123" в поле "password"
     >  И я нажимаю на кнопку "Register"
     >  То я вижу текст "Register success"

**Планируемое время работы:**
2:30 ч

**Comment by Rikling** [comment]
приступил к работе 4:50

**Comment by Rikling** [comment]
приостановлено 6:00

**Comment by Rikling** [comment]
продолжил в 6:20

**Comment by Rikling** [comment]
закончил
