### ISSUE TITLE
Написать функционал для локального хранения БД

### ISSUE THREAD

**Issue by RabigaSB** [sound0terror/LetsPlaySoccer#14]
**Что нужно сделать?**

Создать файл fileDb.js в корневой папке бэка и написать функционал, чтобы хранить данные локально.
Примерно выглядит так:

![image](https://user-images.githubusercontent.com/43925943/61703183-e6acdf00-ad62-11e9-8279-112b45b29edd.png)

**Как это сделать?**

Прочитать раздатку [Express routing, REST API, работа с файлами](https://docs.google.com/document/d/1lg17IzXxU6oUjB5XOD8zxV0HDY-ldWgqahB6ozuk1Iw/edit#)

**Зачем это нужно?**

Чтобы рабочие машины не перегружались

**Критерии приёмки:**

- Должен быть файл с расширением json (локальная база данных)
- Функциональный файл должен уметь:
          - Инициализировать данные
          - Доставать данные
          - Сохранять  данные
          - Добавлять данные
- Пока нужно только для сущностей `Поле`, `Юзер` и `Матч`
чтобы фронт параллельно двигался

**Планируемое время работы:**

**Comment by kasienov2001** [comment]
отказались от локального хранения
