### ISSUE TITLE
Сверстать меню

### ISSUE THREAD

**Issue by RabigaSB** [sound0terror/LetsPlaySoccer#17]
**Что нужно сделать?**

Сверстать меню по дизайну
![image](https://user-images.githubusercontent.com/43925943/61707037-676fd900-ad6b-11e9-98cf-5fd3c1d271b3.png)

**Как это сделать?**

**Зачем это нужно?**

По плану мы должны закончить меню в 2ом майлстоуне. 

**Критерии приёмки:**

- Страницы должны совпадать с дизайном в мобильной версии
- Стили написаны по методологии БЭМ
         в формате block__element--modifier
- Кнопки "Дальше" должны быть рабочими, то есть роуты должны быть настроены
- Все простые иконки должны быть в формате svg, в том числе и логотип
- все ссылки рабочие, направляют на пока пустые страницы с соотвествующими названиями

**Планируемое время работы:**

2:30ч

**Comment by Rikling** [comment]
Приступил к работе в 5:40

**Comment by Rikling** [comment]
приостановлено в 6:20

**Comment by Rikling** [comment]
продолжил работу в 5:40 следующего дня

**Comment by Rikling** [comment]
закончил работу в 6:20 общее время работы: 1:20
