### ISSUE TITLE
Создать компонент FormElement

### ISSUE THREAD

**Issue by RabigaSB** [sound0terror/LetsPlaySoccer#19]
**Что нужно сделать?**

Создать компонент FormElement и использовать его в контейнерах логин и регистрация.

**Как это сделать?**

**Зачем это нужно?**

Чтобы валидацию, обработку ошибок, маску реализовать один раз и переиспользовать  

**Критерии приёмки:**

- FormElement должен показывать ошибку с сервера (можно пока хардкодить)
- Проверка на валидность, 
то есть, если есть поле для номера телефона,
тогда проверить длину (11 цифр) и валидность оператора в Казахстане 
(например, возможные варианты 707, 701. Не правильно: 455, 989)
             Список возможных операторов в Казахстане:
![image](https://user-images.githubusercontent.com/43925943/61784780-2095e800-ae2c-11e9-8ae1-16fa234ad35e.png)

- Должна работать маска, то есть когда юзер вводит свой номер, его номер должен форматироваться как в дизайне, например 8 (747) 343-43-43
- В placeholder'e должно быть "Например,  8 (777) 777-77-77"
чтобы пользователю показать формат

**Планируемое время работы:**
1ч

**Comment by Rikling** [comment]
приступил к работе в 4:20

**Comment by Rikling** [comment]
Закончил рабову в 5:25 заняло 1:05ч
