### ISSUE TITLE
Подготовить презентацию про хуки на Реакте

### ISSUE THREAD

**Issue by RabigaSB** [sound0terror/LetsPlaySoccer#2]
**Конечный результат:** 

Понятная всем презентация простыми своими словами. После презентации все члены команды должны понять что такое хуки, как и когда ими примерно пользоваться.

**План решения:** 

Найти в интернете информацию и структурировать свои полученные знания 

**Мотивация:** 

Мы, как и все продвинутые программисты, должны быть в стеке. Пока мы не понимаем как могут хуки нам облегчить жизнь. 

**Критерии приёмки:**

Должны быть ответы на вопросы:

- Что такое хуки?
- Чем отличаются Lifecycles и hooks (плюсы и минусы)?
- Какие виды есть?
- В каких случаях используется?
- Как мы можем внедрить это в наш проект? Стоит ли?
- И другие вопросы по усмотрению исполнителя задачи

**Планируемое время работы:**
6 часов

**Comment by sound0terror** [comment]
Не актуален
