### ISSUE TITLE
Создать компонент с loader

### ISSUE THREAD

**Issue by RabigaSB** [sound0terror/LetsPlaySoccer#20]
**Что нужно сделать?**

Создать компонент LoaderWrapper и использовать его в контейнерах логин и регистрация.

**Как это сделать?**

Создать компонент Preloader и задать ему стили

**Зачем это нужно?**

Чтобы юзеру было понятно что запросы обрабатываются  

**Критерии приёмки:**

- State loader'а хранится в каждом компоненте отдельно
- Нужно внедрить его в логине и регистрации
- [Здесь ссылка на сам loader](https://codepen.io/glafontaine/pen/geMYaJ)

**Планируемое время работы:**

**Comment by kasienov2001** [comment]
Начал: 20:00 26.07
Прервался: 21:00 26.07
Продолжил: 19:20 29.07
Закончил: 20:20 29.07

Занятое время: 2 часа
