### ISSUE TITLE
Cоздать на бэке Match и Field

### ISSUE THREAD

**Issue by RabigaSB** [sound0terror/LetsPlaySoccer#21]
**Что нужно сделать?**

Создать сущности Match и Field и создать связи между ними и User'ом   
**Как это сделать?**

Прочитать доки и гайд 
https://sequelize.org/master/manual/associations.html
https://medium.com/@eth3rnit3/sequelize-relationships-ultimate-guide-f26801a75554

**Зачем это нужно?**

Чтобы создать функционал

**Критерии приёмки:**

-Создание моделей и рутов на сервере
-Создание связей между моделями 
-Создание сущностей(таблиц в БД)
-Функционал для поля и матчей:
    - Доставать данные
    - Сохранять данные
    - Добавлять данные
чтобы фронт параллельно двигался

**Планируемое время работы:**
12 часов

**Comment by sound0terror** [comment]
**29.07.2019:** Приступил в **21.24**

**Comment by sound0terror** [comment]
**29.07.2019:** Приостановил в **21.45**

**Comment by sound0terror** [comment]
**01.08.2019:** Возобновил работу  в **19.10**
