### ISSUE TITLE
Исправить создание бд

### ISSUE THREAD

**Issue by RabigaSB** [sound0terror/LetsPlaySoccer#28]
**Что нужно сделать?**

Исправить бэк так, чтобы можно было другим участникам запустить сервер, и сразу делать запросы через постман. Чтобы таблица создалась автоматом как в монго при запросе на сервер.

**Как это сделать?**

Прочитать [доку sequelize](https://sequelize.org/master/manual/getting-started.html)

**Зачем это нужно?**

Чтобы таблицу не создавать вручную

**Критерии приёмки:**

Успешный сценарий:

- Запускаешь сервер
- Делаешь к примеру пост запрос
- Приходит ответ с сервера в виде созданного объекта 

**Планируемое время работы:**
1 час

**Comment by sound0terror** [comment]
**Приступил 18:30
Закончил в 19:30
Затраченное время 1 час**
