### ISSUE TITLE
Исправить форму регистрации и логина

### ISSUE THREAD

**Issue by kasienov2001** [sound0terror/LetsPlaySoccer#32]
**Что нужно сделать?**
-убрать не понятную полоску на форме регистрации и логина 
-уменьшить размер формы регистрации и логина для десктопа

**Как это сделать?**
_Просто убрать эту полоску
https://prnt.sc/olkomt
_Сделать форму на десктопе размером с мобильной

**Критерии приёмки:**
-нет черточки
-форму рег/лог уменьшена

**Планируемое время работы:**

**Comment by Rikling** [comment]
приступил к работе в 4:00 закончил в 4:35
