### ISSUE TITLE
Создать футер

### ISSUE THREAD

**Issue by kasienov2001** [sound0terror/LetsPlaySoccer#33]
**Что нужно сделать?**
https://prnt.sc/olktng
https://prnt.sc/olkuka

**Comment by Rikling** [comment]
приступил к работе в 3:15

**Comment by Rikling** [comment]
приступил к работе  в 3:15

**Comment by Rikling** [comment]
приостановлено в 3:45

**Comment by Rikling** [comment]
продолжил в 4:00

**Comment by Rikling** [comment]
закончил в 4:35 потратил 1:20
