### ISSUE TITLE
Создать сущность Field на бэке

### ISSUE THREAD

**Issue by kasienov2001** [sound0terror/LetsPlaySoccer#39]
**Что нужно сделать?**
-Создать сущность Field и все зависимые сущности - Day, Time, Format, Image
-Создать связи между сущностями

**Как это сделать?**
Прочитать доки и гайд 
https://sequelize.org/master/manual/associations.html
https://medium.com/@eth3rnit3/sequelize-relationships-ultimate-guide-f26801a75554

**Критерии приёмки:**

-Создание моделей на сервере
-Создание связей между моделями 
-Создание сущностей(таблиц в БД)

**Планируемое время работы:**
2 часа.

**Comment by sound0terror** [comment]
**02.08.2019** Приступил  в **17.20**

**Comment by sound0terror** [comment]
**02.08.2019** Закончил  в **19.20**
