### ISSUE TITLE
Нарисовать диаграмму вариантов использования (UseCase diagram)

### ISSUE THREAD

**Issue by RabigaSB** [sound0terror/LetsPlaySoccer#5]
**Что нужно сделать?**

Нарисовать более раскрытую похожую схему
![image](https://user-images.githubusercontent.com/43925943/61513974-8c3d1700-aa20-11e9-89bf-74324c00b5ae.png)

**Как это сделать?**

Можно использовать инструменты:
- [draw](https://www.draw.io) 
- [plantuml](http://plantuml.com/) 
- [visic](http://visic.ru/)
- либо другие

**Зачем это нужно?**

- Для понимания проекта
- Для выявления связей между объектами
- Чтобы определить алгоритм разработки проекта
- Чтобы определить вопросы заказчику

**Критерии приёмки:**

- Можно увидеть какие страницы есть, какие отсутствуют 
- Можно увидеть как переходить с одной страницы на другую
- Отмечены где пробелы, чтобы могли уточнить у заказчика

**Планируемое время работы:**
1 день

**Comment by RabigaSB** [comment]
**Что нужно сделать?**

Нарисовать более раскрытую похожую схему
![image](https://user-images.githubusercontent.com/43925943/61513974-8c3d1700-aa20-11e9-89bf-74324c00b5ae.png)

**Как это сделать?**

Можно использовать инструменты:
- [draw](https://www.draw.io) 
- [plantuml](http://plantuml.com/) 
- [visic](http://visic.ru/)
- либо другие

**Зачем это нужно?**

- Для понимания проекта
- Для выявления связей между объектами
- Чтобы определить алгоритм разработки проекта
- Чтобы определить вопросы заказчику

**Критерии приёмки:**

- Можно увидеть какие страницы есть, какие отсутствуют 
- Можно увидеть как переходить с одной страницы на другую
- Отмечены где пробелы, чтобы могли уточнить у заказчика

Планируемое время работы:

**Comment by RabigaSB** [comment]
started at 14:00

**Comment by RabigaSB** [comment]
[UseCase diagram](https://drive.google.com/file/d/1WTkaSG9Leku4M2Xh3hYZa_djUxjoyP-G/view?usp=sharing)

**Comment by sound0terror** [comment]
Напиши время завершения тикета.

**Comment by RabigaSB** [comment]
Закончила в 5утра след.дня когда начала, в итоге примерно день потратила на задачу
